version: '3'

services:

  docker-mysql:

    restart: always

    container_name: docker-mysql-algafood

    image: mysql

    environment:

      MYSQL_DATABASE: algafood

      MYSQL_ROOT_PASSWORD: algafood

      MYSQL_ROOT_HOST: '%'

    volumes:

      - ./sql:/docker-entrypoint-initdb.d
    

    ports:

      - "6033:3306"

    healthcheck:

      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""

      interval: 2s

      timeout: 20s

      retries: 10
